### ISSUE TITLE
Trigger migration even on development deploys

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#331]
## Summary

The reason the migrations do NOT run on `tea` was because the associated `*-requirements.txt` didn't change. We only run migrations when there is a version pinning change. Since the development line entries (`-e git+http://...`) don't change, the migration handler was not triggered.

## Environment

tea & dev

**Comment by pumazi** [comment]
My suggestion would be to add a NOOP task:

```yml
- name: manually trigged migration
  when: manually_trigger_migration is defined
  command: "echo 'NOOP'"
  notify:
    - migrate repository database
```

The key element of change here is the `when` condition & `notify` value.
